// Bitbucket Data Center MCP server — generated by mcpify. Do not hand-edit.

use bitbucket_dc_mcp::core::config_manager::load_config;
use bitbucket_dc_mcp::data::store::cached_store_connection;
use bitbucket_dc_mcp::tools::get_tool::get_operation;

pub async fn run(operation_id: &str) -> anyhow::Result<()> {
    let config = load_config(serde_json::Map::new())?;
    let conn = cached_store_connection(&config.api_version)?
        .lock()
        .unwrap_or_else(std::sync::PoisonError::into_inner);
    let result = get_operation(&conn, operation_id)?;
    println!("{}", serde_json::to_string_pretty(&result)?);
    Ok(())
}
