//! Guided MCP prompts for common Bitbucket Data Center management workflows.
//!
//! Hand-authored (not generated by mcpify): unlike `src/tools/`, which
//! implements the `search`/`get`/`call` business logic mcpify generates
//! from the OpenAPI catalog, this module's `.md` content under `content/`
//! encodes sequencing knowledge — what order to call operations in, which
//! steps gate on which, where steps are independent — that has no
//! generator source of truth. The `#[prompt_router]`-decorated router
//! itself lives in `router.rs`, kept out of this file.

use serde::Deserialize;

use rmcp::schemars;

mod router;

#[derive(Debug, Deserialize, schemars::JsonSchema)]
pub struct MasterWorkflowArgs {
    /// What the user is trying to accomplish, in their own words
    pub goal: Option<String>,
}

#[derive(Debug, Deserialize, schemars::JsonSchema)]
pub struct PullRequestsWorkflowArgs {
    /// Bitbucket project key the repository belongs to
    pub project_key: Option<String>,
    /// Repository slug within the project
    pub repo_slug: Option<String>,
    /// Branch the pull request merges from
    pub source_branch: Option<String>,
    /// Branch the pull request merges into
    pub target_branch: Option<String>,
}

#[derive(Debug, Deserialize, schemars::JsonSchema)]
pub struct MirroringWorkflowArgs {
    /// Project key of the upstream repository being mirrored
    pub upstream_project_key: Option<String>,
    /// Repository slug of the upstream repository being mirrored
    pub upstream_repo_slug: Option<String>,
}

#[derive(Debug, Deserialize, schemars::JsonSchema)]
pub struct MeshWorkflowArgs {
    /// Bitbucket project key of the repository being migrated onto Mesh
    pub project_key: Option<String>,
    /// Repository slug within the project being migrated onto Mesh
    pub repo_slug: Option<String>,
}

#[derive(Debug, Deserialize, schemars::JsonSchema)]
pub struct PrRulesWorkflowArgs {
    /// Bitbucket project key the automation rules apply to
    pub project_key: Option<String>,
    /// Repository slug to scope the rules to a single repository (omit for project-wide rules)
    pub repo_slug: Option<String>,
}

/// Renders a short "Context already provided" block from a prompt's
/// optional arguments, prepended (by each `router.rs` method) to that
/// prompt's static markdown body. Lets the guided prose ask the user only
/// for what's genuinely still missing, without a template-substitution
/// engine — everything invariant lives in the `.md` file, only this
/// per-invocation header is rendered in Rust.
pub fn render_context_header(fields: &[(&str, Option<&str>)]) -> String {
    if fields.is_empty() {
        return "## Context already provided\n\n(this prompt takes no arguments)\n".to_string();
    }

    let mut known = String::new();
    let mut missing = String::new();
    for (name, value) in fields {
        match value {
            Some(v) => known.push_str(&format!("- `{name}`: {v}\n")),
            None => missing.push_str(&format!("- `{name}`\n")),
        }
    }
    if known.is_empty() {
        known.push_str("- (none)\n");
    }
    if missing.is_empty() {
        missing.push_str("- (none)\n");
    }

    format!(
        "## Context already provided\n\n{known}\n## Still missing (ask the user if needed)\n\n{missing}"
    )
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn empty_fields_render_a_no_arguments_note() {
        let header = render_context_header(&[]);
        assert_eq!(
            header,
            "## Context already provided\n\n(this prompt takes no arguments)\n"
        );
    }

    #[test]
    fn all_supplied_fields_list_no_missing_entries() {
        let header =
            render_context_header(&[("project_key", Some("PROJ")), ("repo_slug", Some("repo"))]);
        assert!(header.contains("- `project_key`: PROJ\n"));
        assert!(header.contains("- `repo_slug`: repo\n"));
        assert!(header.contains("## Still missing (ask the user if needed)\n\n- (none)\n"));
    }

    #[test]
    fn all_missing_fields_list_no_known_entries() {
        let header = render_context_header(&[("project_key", None), ("repo_slug", None)]);
        assert!(header.contains("## Context already provided\n\n- (none)\n"));
        assert!(header.contains("- `project_key`\n"));
        assert!(header.contains("- `repo_slug`\n"));
    }

    #[test]
    fn mixed_fields_split_between_known_and_missing() {
        let header = render_context_header(&[
            ("project_key", Some("PROJ")),
            ("repo_slug", None),
            ("source_branch", Some("feature/x")),
            ("target_branch", None),
        ]);
        assert!(header.contains("- `project_key`: PROJ\n"));
        assert!(header.contains("- `source_branch`: feature/x\n"));
        let missing_section = header
            .split("## Still missing (ask the user if needed)\n\n")
            .nth(1)
            .unwrap();
        assert!(missing_section.contains("- `repo_slug`\n"));
        assert!(missing_section.contains("- `target_branch`\n"));
        assert!(!missing_section.contains("project_key"));
    }
}
